name: Test p1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./p1

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: build program
        run: javac -sourcepath ./  ./launcher/BuffyVampireSlayer.java # Path to the main file and source folder
        working-directory: ${{env.working-directory}}

      - name: execute program
        if: ${{ success() }} # Only starts if the previous steps worked
        run: java launcher.BuffyVampireSlayer EASY 5 < ../../test_cases/easy_s5_0.txt # Path to the .class of main, arguments for the game and the input file
        working-directory: ./p1
